source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxOptional Examples' do
  pod 'RxOptional', :path => '../'
  pod 'RxSwift', '~> 2.0'
  pod 'RxCocoa', '~> 2.0'
end

target 'RxOptional Tests' do
  pod 'RxOptional', :path => '../'
  pod 'RxSwift', '~> 2.0'
  pod 'RxCocoa', '~> 2.0'

  pod 'Quick'
  pod 'Nimble'
end
