source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

link_with 'RxOptional Examples', 'Examples'

target 'RxOptional Examples', :exclusive => true do
  pod 'RxOptional', :path => '../'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift-3.0'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift-3.0'
end

target 'RxOptional Tests', :exclusive => true do
  pod 'RxOptional', :path => '../'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift-3.0'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift-3.0'

  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'master'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'
end
