source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

link_with 'RxOptional Examples', 'Examples'

target 'RxOptional Examples', :exclusive => true do
  pod 'RxOptional', :path => '../'
  pod 'RxSwift', '~> 2.0'
  pod 'RxCocoa', '~> 2.0'
end

target 'RxOptional Tests', :exclusive => true do
  pod 'RxOptional', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'
end
